name: 'Test and Build'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@akiratatsuhisa'

      - name: Clean install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}

      - name: Run test eslint and prettier
        run: npm run test:lint

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          registry-url: 'https://npm.pkg.github.com'
          scope: '@akiratatsuhisa'

      - name: Clean install dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT }}

      - name: Run build
        run: npm run build
